Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2022-11, with the labels that each got.

#35 Adding shared utils, interfaces, client services
  models/interfaces.ts
  public/models/interfaces.ts
  public/models/types.ts
  public/services/AlertsService.ts
  public/services/DetectorService.ts
  public/services/FieldMappingService.ts
  public/services/NotificationsService.ts
  public/services/RuleService.ts
  public/services/index.ts
  public/utils/constants.ts
  public/utils/helpers.ts
  public/utils/helpers.tsx
Labels: backport 2.x, backport 2.4

#37 Overview UI page updates
  public/pages/Overview/components/GettingStarted/GettingStartedPopup.tsx
  public/pages/Overview/components/Widgets/DetectorsWidget.tsx
  public/pages/Overview/components/Widgets/RecentAlertsWidget.tsx
  public/pages/Overview/components/Widgets/RecentFindingsWidget.tsx
  public/pages/Overview/components/Widgets/Summary.tsx
  public/pages/Overview/components/Widgets/TableWidget.tsx
  public/pages/Overview/components/Widgets/TopRulesWidget.tsx
  public/pages/Overview/components/Widgets/WidgetContainer.tsx
  public/pages/Overview/containers/Overview/Overview.scss
  public/pages/Overview/containers/Overview/Overview.tsx
  public/pages/Overview/containers/Overview/index.ts
  public/pages/Overview/models/OverviewViewModel.ts
  public/pages/Overview/models/interfaces.ts
  public/pages/Overview/utils/constants.ts
  public/pages/Overview/utils/dummyData.ts
  public/pages/Overview/utils/helpers.ts
Labels: backport 2.x, backport 2.4

#36 Added/updated service wrappers used for making REST calls to security analytics backend plugin
  server/clusters/addAlertsMethods.ts
  server/clusters/addFieldMappingMethods.ts
  server/clusters/addFindingsMethods.ts
  server/clusters/addNotificationsMethods.ts
  server/clusters/addRuleMethods.ts
  server/clusters/securityAnalyticsPlugin.ts
  server/models/interfaces/Alerts.ts
  server/models/interfaces/Detectors.ts
  server/models/interfaces/FieldMappings.ts
  server/models/interfaces/Findings.ts
  server/models/interfaces/Notifications.ts
  server/models/interfaces/Rules.ts
  server/models/interfaces/index.ts
  server/plugin.ts
  server/routes/AlertRoutes.ts
  server/routes/DetectorRoutes.ts
  server/routes/FieldMappingRoutes.ts
  server/routes/NotificationsRoutes.ts
  server/routes/RuleRoutes.ts
  server/routes/index.ts
  server/services/AlertService.ts
  server/services/DetectorService.ts
  server/services/FieldMappingService.ts
  server/services/NotificationsService.ts
  server/services/RuleService.ts
  server/services/index.ts
  server/utils/constants.ts
Labels: backport 2.x, backport 2.4

#39 Updated create detector UX
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/models/interfaces.ts
  public/pages/CreateDetector/components/ConfigureAlerts/utils/constants.ts
  public/pages/CreateDetector/components/ConfigureAlerts/utils/helpers.ts
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldMappingsTable.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldNameSelector.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/utils/constants.ts
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRules.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRulesTable.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/types/interfaces.ts
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/utils/constants.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDetails/DetectorBasicDetailsForm.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/CustomCron.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/Daily.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/DetectorSchedule.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/Interval.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/Monthly.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/Weekly.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/components/ReviewAndCreate/containers/ReviewAndCreate.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/CreateDetector/models/interfaces.ts
Labels: backport 2.x, backport 2.4

#40 Added detectors view/edit ux
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/DetectorBasicDetailsView.tsx
  public/pages/Detectors/components/DetectorRulesView/DetectorRulesView.tsx
  public/pages/Detectors/components/FieldMappingsView/FieldMappingsView.tsx
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateFieldMappings/UpdateFieldMappings.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.tsx
  public/pages/Detectors/containers/Detector/Detector.tsx
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/Detectors/Detectors.tsx
  public/pages/Detectors/utils/constants.ts
  public/pages/Detectors/utils/helpers.ts
Labels: backport 2.x, backport 2.4

#41 Added/updated main and rules pages
  public/pages/Main/Main.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
  public/pages/Rules/containers/Rules/components/Create/Create.tsx
  public/pages/Rules/containers/Rules/components/Create/index.scss
  public/pages/Rules/containers/Rules/components/Create/index.ts
  public/pages/Rules/containers/Rules/components/Duplicate/Duplicate.tsx
  public/pages/Rules/containers/Rules/components/Duplicate/index.tsx
  public/pages/Rules/containers/Rules/components/Edit/Edit.tsx
  public/pages/Rules/containers/Rules/components/Edit/Visual/Visual.tsx
  public/pages/Rules/containers/Rules/components/Edit/Visual/index.scss
  public/pages/Rules/containers/Rules/components/Edit/Visual/index.tsx
  public/pages/Rules/containers/Rules/components/Edit/YAML/YAML.tsx
  public/pages/Rules/containers/Rules/components/Edit/YAML/index.tsx
  public/pages/Rules/containers/Rules/components/Edit/index.ts
  public/pages/Rules/containers/Rules/components/Import/Import.tsx
  public/pages/Rules/containers/Rules/components/Import/index.ts
  public/pages/Rules/containers/Rules/components/Main/Main.tsx
  public/pages/Rules/containers/Rules/components/Main/index.ts
  public/pages/Rules/containers/Rules/components/Table/Table.tsx
  public/pages/Rules/containers/Rules/components/Table/index.ts
  public/pages/Rules/containers/Rules/components/View/View.tsx
  public/pages/Rules/containers/Rules/components/View/index.scss
  public/pages/Rules/containers/Rules/components/View/index.ts
  public/pages/Rules/lib/UIComponents/Flyout.tsx
  public/pages/Rules/lib/UIComponents/index.ts
  public/pages/Rules/lib/helpers/index.ts
Labels: backport 2.x, backport 2.4

#38 Updated alerts and findings UI pages
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Alerts/utils/constants.ts
  public/pages/Findings/components/CreateAlertFlyout.tsx
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Findings/models/interfaces.ts
  public/security_analytics_app.tsx
Labels: backport 2.x, backport 2.4

#56 Fixed edit page refresh bug. Implemented toast notifications. Refactored some components based on feedback.
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRulesTable.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDetails/DetectorBasicDetailsForm.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorType/DetectorType.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/components/ReviewAndCreate/containers/ReviewAndCreate.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/DetectorRulesView/DetectorRulesView.tsx
  public/pages/Detectors/components/FieldMappingsView/FieldMappingsView.tsx
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateFieldMappings/UpdateFieldMappings.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.tsx
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/Detectors/Detectors.tsx
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Main/Main.tsx
  public/pages/Overview/containers/Overview/Overview.tsx
  public/pages/Overview/models/OverviewViewModel.ts
  public/utils/constants.ts
  public/utils/helpers.tsx
  public/utils/validation.ts
Labels: backport 2.x, backport 2.4

#59 Redirect to rules page when payload empty for edit or duplicate pages; Improved import page
  public/pages/Main/Main.tsx
  public/pages/Overview/containers/Overview/Overview.tsx
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
Labels: backport 2.x, backport 2.4

#60 Added some infrastructure to run cypress tests.
  .github/workflows/cypress-workflow.yml
  cypress/plugins/index.ts
  cypress/support/commands.js
  cypress/support/constants.js
  cypress/support/index.d.ts
  cypress/support/index.js
Labels: backport 2.x, backport 2.4

#65 Drafted 2.4 release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4

#70 Added toast notifications for failure cases in rule creation/edit
  public/pages/Main/Main.tsx
  public/pages/Rules/components/RuleEditor/RuleEditor.tsx
  public/pages/Rules/containers/CreateRule/CreateRule.tsx
  public/pages/Rules/containers/DuplicateRule/DuplicateRule.tsx
  public/pages/Rules/containers/EditRule/EditRule.tsx
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/utils/helpers.tsx
Labels: backport 2.x, backport 2.4

#71 Added experimental indicator; fixed edit detector pages
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.tsx
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Main/Main.tsx
  public/pages/Overview/models/interfaces.ts
  public/pages/Rules/containers/CreateRule/CreateRule.tsx
  public/pages/Rules/containers/DuplicateRule/DuplicateRule.tsx
  public/pages/Rules/containers/EditRule/EditRule.tsx
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
  public/utils/constants.ts
Labels: backport 2.x, backport 2.4

#72 Fixed a bug impacting redirection to monitor details page after creating a monitor.
  public/pages/CreateDetector/containers/CreateDetector.tsx
Labels: backport 2.x, backport 2.4

#75 Implemented integration test for create rule workflow.
  cypress/integration/rules_spec.js
  cypress/support/commands.js
  cypress/support/constants.js
  public/pages/Rules/components/RuleContentViewer/RuleContentViewer.tsx
  public/pages/Rules/components/RuleEditor/FieldTextArray.tsx
  public/pages/Rules/components/RuleEditor/RuleEditor.tsx
  public/pages/Rules/components/RuleViewerFlyout/RuleViewerFlyout.tsx
  public/pages/Rules/containers/CreateRule/CreateRule.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
  public/pages/Rules/utils/helpers.tsx
Labels: backport 2.x, backport 2.4

#77 Backporting files from main to 2.x.
  cypress/integration/rules_spec.js
  cypress/support/commands.js
  cypress/support/constants.js
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.tsx
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Main/Main.tsx
  public/pages/Overview/containers/Overview/Overview.tsx
  public/pages/Overview/models/interfaces.ts
  public/pages/Rules/components/RuleContentViewer/RuleContentViewer.tsx
  public/pages/Rules/components/RuleEditor/FieldTextArray.tsx
  public/pages/Rules/components/RuleEditor/RuleEditor.tsx
  public/pages/Rules/components/RuleViewerFlyout/RuleViewerFlyout.tsx
  public/pages/Rules/containers/CreateRule/CreateRule.tsx
  public/pages/Rules/containers/DuplicateRule/DuplicateRule.tsx
  public/pages/Rules/containers/EditRule/EditRule.tsx
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
  public/pages/Rules/utils/helpers.tsx
  public/utils/constants.ts
Labels: backport 2.4

#82 Fixed an import line that was missing EuiButton.
  public/pages/Overview/containers/Overview/Overview.tsx
Labels: backport 2.4

#85 Edited release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.4.0.0.md
Labels: backport 2.x, backport 2.4

#86 Validating detection, name and author fields for Rules Create and Update operations
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/utils/helpers.tsx
Labels: backport 2.x, backport 2.4

#84 Implemented input validation for the detector description field.
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDetails/DetectorBasicDetailsForm.tsx
  public/utils/validation.ts
Labels: backport 2.x, backport 2.4

#95 Miscellaneous bug fixes
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDetails/DetectorBasicDetailsForm.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/components/ReviewAndCreate/containers/ReviewAndCreate.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/UpdateFieldMappings/UpdateFieldMappings.tsx
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Findings/components/CreateAlertFlyout.tsx
  public/pages/Main/Main.tsx
  public/pages/Overview/components/Widgets/Summary.tsx
  public/pages/Rules/components/RuleEditor/RuleEditor.tsx
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/utils/helpers.tsx
  public/utils/constants.ts
  public/utils/validation.ts
Labels: backport 2.x, backport 2.4

#96 UI Bug fixes
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/utils/constants.ts
  public/utils/helpers.tsx
  server/models/interfaces/Detectors.ts
  server/services/DetectorService.ts
Labels: backport 2.x, backport 2.4

#101 Fixed display format for info on alert details flyout. Disabled various buttons when executing API calls.
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Detectors/containers/Detectors/Detectors.tsx
Labels: backport 2.x, backport 2.4

#105 Fix rules payload in create detector and some reference errors
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDetails/DetectorBasicDetailsForm.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/DetectorRulesView/DetectorRulesView.tsx
  public/pages/Detectors/components/FieldMappingsView/FieldMappingsView.tsx
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
Labels: backport 2.x, backport 2.4

#108 Use lower case for detector type when editing detector
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
Labels: backport 2.x, backport 2.4

#149 Adjusted OSD version used by test workflows.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x

#159 Add loader to Rules table
  public/pages/Rules/components/RulesTable/RulesTable.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
Labels: backport 2.x

#140 Updated breadcrums for Rules pages
  public/pages/Rules/containers/CreateRule/CreateRule.tsx
  public/pages/Rules/containers/DuplicateRule/DuplicateRule.tsx
  public/pages/Rules/containers/EditRule/EditRule.tsx
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/utils/helpers.tsx
Labels: backport 2.x

#148 [FEATURE] Get started | Add Alert info in the Get started pop-up #129
  public/pages/Overview/components/GettingStarted/GetStartedStep.tsx
  public/pages/Overview/components/GettingStarted/GettingStartedPopup.tsx
  public/pages/Overview/utils/constants.ts
Labels: backport 2.x

#145 Refactor fields mapping to use combo box component
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldNameSelector.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
Labels: backport 2.x

#138 Fix stepper state
  public/pages/CreateDetector/containers/CreateDetector.tsx
Labels: backport 2.x

#157 Add EuiHealth component to DetectorDetails
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
Labels: backport 2.x

#135 Implemented cypress tests for acknowledging alerts.
  cypress/fixtures/sample_alias_mappings.json
  cypress/fixtures/sample_detector.json
  cypress/integration/1_detectors.spec.js
  cypress/integration/2_rules.spec.js
  cypress/integration/3_alerts.spec.js
  cypress/support/commands.js
  cypress/support/constants.js
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/utils/helpers.tsx
Labels: backport 2.x
