Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-05, with the labels that each got.

#566 Fixed cypress and unit test workflows after bumping main to 3.0.
  .github/workflows/cypress-workflow.yml
  test/jest.config.js
Labels: v3.0.0

#561 UX improvements for correlation engine
  public/pages/Correlations/components/CorrelationGraph.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
  public/pages/Correlations/utils/constants.tsx
Labels: v2.8.0

#576 [Overview page] Fixed recent alerts & finding order; count for pie chart
  public/pages/Overview/components/Widgets/RecentAlertsWidget.tsx
  public/pages/Overview/components/Widgets/RecentFindingsWidget.tsx
  public/pages/Overview/components/Widgets/TopRulesWidget.tsx
Labels: backport 2.x

#581 rule's cypress tests update
  cypress/integration/2_rules.spec.js
Labels: backport 2.x

#597 Added 2.8 release notes
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.8.0.0.md
Labels: backport 2.x

#594 Update selection panel component for the "Create detection rule"
  cypress/integration/2_rules.spec.js
  public/app.scss
  public/pages/Rules/components/RuleEditor/DetectionVisualEditor.scss
  public/pages/Rules/components/RuleEditor/DetectionVisualEditor.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorForm.tsx
  public/pages/Rules/components/RuleEditor/components/YamlRuleEditorComponent/RuleTagsComboBox.tsx
  public/pages/Rules/containers/CreateRule/CreateRule.tsx
Labels: backport 2.x, backport 2.8

#584 Use user provided end date for calculating the end time of the x-axis time range
  public/pages/Overview/utils/helpers.ts
Labels: backport 2.x, backport 2.8
