Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-04, with the labels that each got.

#490 Adds field mappings to edit detector pages
  cypress/integration/1_detectors.spec.js
  public/app.scss
  public/components/ContentPanel/ContentPanel.tsx
  public/pages/Alerts/containers/Alerts/__snapshots__/Alerts.test.tsx.snap
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldNameSelector.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/types/interfaces.ts
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/components/ReviewFieldMappings/ReviewFieldMappings.scss
  public/pages/Detectors/components/ReviewFieldMappings/ReviewFieldMappings.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/components/UpdateFieldMappings/UpdateFieldMappings.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/pages/Detectors/components/UpdateRules/__snapshots__/UpdateDetectorRules.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/containers/FieldMappings/EditFieldMapping.tsx
  public/pages/Detectors/containers/FieldMappings/__snapshots__/EditFieldMappings.test.tsx.snap
  public/pages/Main/Main.tsx
  types/Rule.ts
Labels: backport 2.x

#501 Refactor and move field mapping to first the page of create detector feature
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRules.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/DetectorSchedule.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/Interval.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorType/DetectorType.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/components/ReviewAndCreate/containers/ReviewAndCreate.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/CreateDetector/models/types.ts
  public/pages/CreateDetector/utils/constants.ts
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/FieldMappingsView/FieldMappingsView.tsx
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.tsx
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
Labels: backport 2.x

#494 Provide empty states for Findings and Alerts page
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Alerts/containers/Alerts/__snapshots__/Alerts.test.tsx.snap
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Overview/containers/Overview/Overview.tsx
Labels: backport 2.x

#508 Bumped version to 2.7.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  opensearch_dashboards.json
  package.json
Labels: backport 2.x

#505 Minor bug fixes
  public/app.scss
  public/pages/Detectors/components/AlertTriggerView/__snapshots__/AlertTriggerView.test.tsx.snap
  public/pages/Detectors/components/DetectorBasicDetailsView/__snapshots__/DetectorBasicDetailsView.test.tsx.snap
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/utils/constants.ts
  public/utils/helpers.tsx
Labels: backport 2.x

#493 Create global state object for async requests
  cypress/integration/1_detectors.spec.js
  public/app.scss
  public/pages/Alerts/containers/Alerts/__snapshots__/Alerts.test.tsx.snap
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldNameSelector.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/components/UpdateAlertConditions/__snapshots__/UpdateAlertConditions.test.tsx.snap
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/containers/Detectors/__snapshots__/Detectors.test.tsx.snap
  public/pages/Main/Main.tsx
  public/pages/Main/components/Callout.scss
  public/pages/Main/components/Callout.tsx
  public/store/DataStore.ts
  public/store/DetectorsStore.test.ts
  public/store/DetectorsStore.ts
  public/store/DetectorsStore.tsx
  test/mocks/services/browserHistory.mock.ts
  test/mocks/services/notifications/NotificationsStart.mock.ts
Labels: backport 2.x

#503 Create detector refactor alert triggers per mocks
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/__snapshots__/AlertConditionPanel.test.tsx.snap
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/CreateDetector/utils/constants.ts
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/AlertTriggerView/__snapshots__/AlertTriggerView.test.tsx.snap
  public/pages/Detectors/components/FieldMappingsView/FieldMappingsView.tsx
  public/pages/Detectors/components/FieldMappingsView/__snapshots__/FieldMappingsView.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.tsx
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
Labels: backport 2.x

#504 Update detector details component
  cypress/integration/1_detectors.spec.js
  public/pages/Detectors/components/DetectorBasicDetailsView/DetectorBasicDetailsView.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/__snapshots__/DetectorBasicDetailsView.test.tsx.snap
  public/pages/Detectors/components/DetectorRulesView/DetectorRulesView.tsx
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/components/UpdateAlertConditions/__snapshots__/UpdateAlertConditions.test.tsx.snap
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/containers/Detectors/__snapshots__/Detectors.test.tsx.snap
  public/pages/Detectors/containers/FieldMappings/__snapshots__/EditFieldMappings.test.tsx.snap
  test/mocks/Alerts/PeriodSchedule.mock.ts
Labels: backport 2.x

#523 Added 2.7 release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7

#515 Feature] deleting detectors should delete all related dashboards (including index patterns and visualisations)
  cypress/fixtures/integration_tests/rule/create_network_rule.json
  cypress/fixtures/sample_network_index_settings.json
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/DetectorBasicDetailsView.tsx
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Main/Main.tsx
  public/services/IndexPatternsService.ts
  public/services/SavedObjectService.ts
  public/store/DetectorsStore.tsx
  types/services/ISavedObjectsService.ts
Labels: backport 2.x, backport 2.7

#532 [Backport 2.x] 2.7 manual backports.
  MAINTAINERS.md
  cypress/fixtures/integration_tests/rule/create_network_rule.json
  cypress/fixtures/sample_network_index_settings.json
  cypress/integration/2_rules.spec.js
  models/interfaces.ts
  package.json
  public/app.scss
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRules.tsx
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/AlertTriggerView/__snapshots__/AlertTriggerView.test.tsx.snap
  public/pages/Detectors/components/DetectorBasicDetailsView/DetectorBasicDetailsView.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/__snapshots__/DetectorBasicDetailsView.test.tsx.snap
  public/pages/Detectors/components/UpdateAlertConditions/__snapshots__/UpdateAlertConditions.test.tsx.snap
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Main/Main.tsx
  public/pages/Overview/utils/__snapshots__/helper.test.ts.snap
  public/pages/Overview/utils/helpers.ts
  public/pages/Rules/components/RuleEditor/RuleEditor.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorFormModel.ts
  public/services/IndexPatternsService.ts
  public/services/SavedObjectService.ts
  public/store/DetectorsStore.tsx
  public/utils/constants.ts
  public/utils/helpers.tsx
  public/utils/validation.ts
  test/mocks/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.mock.ts
  tsconfig.json
  types/services/ISavedObjectsService.ts
  yarn.lock
Labels: backport 2.7

#524 Correlation engine ux
  package.json
  public/app.scss
  public/models/interfaces.ts
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Correlations/Correlations.scss
  public/pages/Correlations/components/CorrelationGraph.tsx
  public/pages/Correlations/components/DeleteModal.tsx
  public/pages/Correlations/components/ExperimentalBanner.tsx
  public/pages/Correlations/components/FilterGroup.tsx
  public/pages/Correlations/components/FindingCard.tsx
  public/pages/Correlations/containers/CorrelationRuleFormModel.ts
  public/pages/Correlations/containers/CorrelationRules.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/pages/Correlations/utils/constants.tsx
  public/pages/Correlations/utils/helpers.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRulesTable.tsx
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/utils/constants.ts
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Findings/utils/constants.ts
  public/pages/Main/Main.tsx
  public/pages/Rules/utils/constants.ts
  public/pages/Rules/utils/helpers.tsx
  public/react-graph-vis.d.ts
  public/security_analytics_app.tsx
  public/services/CorrelationService.ts
  public/services/DetectorService.ts
  public/services/IndexService.ts
  public/services/index.ts
  public/store/CorrelationsStore.ts
  public/store/DataStore.ts
  public/utils/constants.ts
  server/clusters/addCorrelationMethods.ts
  server/clusters/securityAnalyticsPlugin.ts
  server/models/interfaces/Detectors.ts
  server/models/interfaces/index.ts
  server/plugin.ts
  server/routes/CorrelationRoutes.ts
  server/routes/IndexRoutes.ts
  server/routes/index.ts
  server/services/CorrelationService.ts
  server/services/DetectorService.ts
  server/services/IndexService.ts
  server/services/index.ts
  server/utils/constants.ts
  types/Correlations.ts
  types/index.ts
  types/services/IBrowserServices.ts
  types/services/ICorrelationService.ts
  yarn.lock
Labels: backport 2.x, backport 2.7

#538 Removed duplicate import for EuiSpacer
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
Labels: backport 2.x, backport 2.7

#547 Updated 2.7 release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.7.0.0.md
Labels: backport 2.x, backport 2.7

#556 Bumped main branch version to 3.0.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  opensearch_dashboards.json
  package.json
Labels: v3.0.0
