Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-07, with the labels that each got.

#643 Added support for editing correlation rule
  public/pages/Correlations/containers/CorrelationRules.tsx
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/pages/Main/Main.tsx
  public/pages/Rules/components/RuleEditor/components/SelectionExpField.tsx
  public/services/CorrelationService.ts
  public/store/CorrelationsStore.ts
  public/utils/constants.ts
  public/utils/validation.ts
  server/clusters/addCorrelationMethods.ts
  server/routes/CorrelationRoutes.ts
  server/services/CorrelationService.ts
  server/utils/constants.ts
  types/Correlations.ts
Labels: backport 2.x, backport 2.9

#647 Removed experimental banner
  public/pages/Correlations/components/ExperimentalBanner.tsx
  public/pages/Correlations/containers/CorrelationRules.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/pages/Main/Main.tsx
Labels: backport 2.x, backport 2.9

#650 Added 2.9 release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.9.0.0.md
Labels: backport 2.x, backport 2.9

#653 Added new log type for vpc flow
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/utils/constants.ts
  public/pages/Rules/utils/constants.ts
Labels: backport 2.x, backport 2.9

#656 Bumped tough-cookie, and semver versions.
  package.json
  yarn.lock
Labels: backport 2.9

#665 Pass sortOrder and size params when getting findings and alerts
  public/services/AlertsService.ts
  public/services/FindingsService.ts
  server/clusters/addAlertsMethods.ts
  server/clusters/addFindingsMethods.ts
  server/models/interfaces/Alerts.ts
  server/models/interfaces/Findings.ts
  server/routes/AlertRoutes.ts
  server/routes/FindingsRoutes.ts
  server/services/AlertService.ts
  server/services/FindingsService.ts
Labels: backport 2.x, backport 2.5, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#674 [Custom log types] Show log types table, Log type creation workflow
  .github/workflows/cypress-workflow.yml
  cypress/integration/1_detectors.spec.js
  public/components/ContentPanel/ContentPanel.tsx
  public/models/interfaces.ts
  public/pages/Alerts/containers/Alerts/__snapshots__/Alerts.test.tsx.snap
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/LogTypes/components/LogTypeDetailsTab.tsx
  public/pages/LogTypes/components/LogTypeDetectionRules.tsx
  public/pages/LogTypes/containers/LogTypeDetails.tsx
  public/pages/LogTypes/containers/LogTypes.tsx
  public/pages/LogTypes/utils/constants.ts
  public/pages/LogTypes/utils/helpers.tsx
  public/pages/Main/Main.tsx
  public/security_analytics_app.tsx
  public/services/LogTypeService.ts
  public/services/index.ts
  public/store/DataStore.ts
  public/store/DetectorsStore.tsx
  public/store/LogTypeStore.ts
  public/utils/constants.ts
  server/clusters/addLogTypeMethods.ts
  server/clusters/securityAnalyticsPlugin.ts
  server/models/interfaces/index.ts
  server/plugin.ts
  server/routes/LogTypeRoutes.ts
  server/routes/index.ts
  server/services/LogTypeService.ts
  server/utils/constants.ts
  test/mocks/services/browserHistory.mock.ts
  types/LogTypes.ts
  types/index.ts
Labels: backport 2.x, backport 2.9
