Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-01, with the labels that each got.

#289 [FEATURE] Detector must have at least one alert set #288
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
Labels: backport 2.x

#296 Cypress windows tests fix
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  tsconfig.json
  yarn.lock
Labels: backport 2.x

#307 Updated field mapping UX; disabled windows run for cypress
  .github/workflows/cypress-workflow.yml
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/utils/constants.ts
  public/pages/Detectors/components/FieldMappingsView/FieldMappingsView.tsx
  public/pages/Detectors/components/UpdateFieldMappings/UpdateFieldMappings.tsx
  public/pages/Detectors/containers/FieldMappings/EditFieldMapping.tsx
Labels: backport 2.x

#309 Status chart colors update
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Overview/utils/__snapshots__/helper.test.ts.snap
  public/pages/Overview/utils/helpers.ts
Labels: backport 2.x

#303 Remove experimental banner
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Main/Main.tsx
Labels: backport 2.x

#310 Improve rules view in detector details
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRulesTable.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/utils/constants.tsx
Labels: backport 2.x

#292 Rule details flyout on detector view page
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/DetectorRulesView/DetectorRulesView.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/pages/Rules/models/RulesViewModelActor.ts
Labels: backport 2.x

#308 Improve alert condition input placeholders
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
Labels: backport 2.x

#318 Adds findings alerts legend in overview page
  public/pages/Overview/components/Widgets/Summary.tsx
  public/pages/Overview/utils/__snapshots__/helper.test.ts.snap
  public/pages/Overview/utils/helpers.ts
Labels: backport 2.x

#320 Feature/hide view docs button
  public/pages/Findings/components/FindingDetailsFlyout.tsx
Labels: backport 2.x

#322 Feature/294 styling issues
  public/pages/Rules/components/RuleContentViewer/RuleContentViewer.tsx
Labels: backport 2.x

#317 Wait for field mapping creation to succeed before detector creation API call
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/utils/validation.ts
Labels: backport 2.x

#328 Patch missing detector_id with data already on UI
  public/pages/Alerts/containers/Alerts/Alerts.tsx
Labels: backport 2.x

#297 Bumped version to 2.5.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  cypress/integration/1_detectors.spec.js
  opensearch_dashboards.json
  package.json
Labels: backport 2.x

#333 Feature/data source single select field
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
Labels: backport 2.x

#330 Improved field mapping UX
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldMappingsTable.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
Labels: backport 2.x

#329 Drafted 2.5 release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.5.0.0.md
Labels: backport 2.x, backport 2.5

#338 Suppressed unnecessary error toast for custom rules
  public/pages/Overview/models/OverviewViewModel.ts
Labels: backport 2.x, backport 2.5

#343 Loading spinner added to Rules in Define detector step
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRules.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
Labels: backport 2.x, backport 2.5

#350 Switch active alert colors
  public/pages/Overview/utils/helpers.ts
Labels: backport 2.x, backport 2.5

#353 Provide all unmapped fields when editing Rule field mapping
  public/pages/Detectors/containers/FieldMappings/EditFieldMapping.tsx
Labels: backport 2.x, backport 2.5

#348 Chart tooltips delay fix
  public/utils/helpers.tsx
Labels: backport 2.x

#360 Fix windows-latest cypress tests
  .github/workflows/cypress-workflow.yml
  cypress.json
  cypress/integration/1_detectors.spec.js
  cypress/support/commands.js
  cypress/support/index.d.ts
Labels: backport 2.x

#365 Cypress custom commands
  cypress/integration/1_detectors.spec.js
  cypress/integration/2_rules.spec.js
  cypress/integration/4_findings.spec.js
  cypress/support/commands.js
  cypress/support/detectors.js
  cypress/support/index.d.ts
  cypress/support/indexes.js
  cypress/support/rules.js
  cypress/support/typings.js
Labels: backport 2.x

#298 Update rule type lists in multiple pages
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/Detectors/containers/Detectors/Detectors.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Overview/components/Widgets/DetectorsWidget.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorForm.tsx
  public/pages/Rules/utils/constants.ts
  public/pages/Rules/utils/helpers.tsx
  public/utils/helpers.tsx
Labels: backport 2.x, 2.6

#367 Feature/flyout alert name validation
  public/pages/Findings/components/CreateAlertFlyout.tsx
Labels: backport 2.x

#363 Fixed README.
  README.md
Labels: backport 2.x

#377 Feature/add role edit cypress tests
  cypress.json
  cypress/integration/1_detectors.spec.js
  cypress/integration/2_rules.spec.js
Labels: backport 2.x

#369 Adjust styling for Finding details flyout
  cypress/integration/3_alerts.spec.js
  public/pages/Findings/components/FindingDetailsFlyout.tsx
Labels: backport 2.x

#379 Bugfix/interval field can be empty
  .github/workflows/cypress-workflow.yml
  cypress.json
  cypress/integration/1_detectors.spec.js
  cypress/integration/2_rules.spec.js
  cypress/integration/3_alerts.spec.js
  cypress/support/detectors.js
  cypress/support/indexes.js
  cypress/support/rules.js
  cypress/support/typings.js
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/Interval.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
Labels: backport 2.x

#389 Adjusted unit and cypress workflows to use the opensearch dashboards 2.5.0 tag instead of the 2.5 branch as a reference.
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x

#366 Create index pattern - modal popup
  cypress/integration/4_findings.spec.js
  opensearch_dashboards.json
  public/models/interfaces.ts
  public/pages/Findings/components/CreateIndexPatternForm.tsx
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Main/Main.tsx
  public/plugin.ts
  public/security_analytics_app.tsx
  public/services/IndexPatternsService.ts
  public/services/index.ts
Labels: backport 2.x

#388 Hide Security Analytics sidebar for edit detector pages
  public/pages/Main/Main.tsx
Labels: backport 2.x

#396 [FEATURE] Add "Create detector" item to the breadcrumbs #394
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/utils/constants.ts
Labels: backport 2.x

#387 Detector details page wrappers fix
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Rules/components/RulesTable/RulesTable.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
Labels: backport 2.x
