Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-11, with the labels that each got.

#777 Onboard jenkins prod docker images to github actions
  .github/workflows/dco.yml
  .github/workflows/unit-tests-workflow.yml
Labels: enhancement, backport 2.x

#785 Added release notes for 2.11.1
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.11.1.0.md
Labels: backport 2.x, backport 2.11

#797 Update release notes 2.11.1
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.11.1.0.md
Labels: backport 2.x, backport 2.11

#791 Added null check for threat intel alias fields
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  server/models/interfaces/FieldMappings.ts
Labels: backport 2.x

#796 Make notifications optional
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/__snapshots__/AlertConditionPanel.test.tsx.snap
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
Labels: backport 2.x

#801 Separated fields for every index in correlation rule creation/update
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
Labels: backport 2.x, backport 2.9, backport 2.10, backport 2.11

#804 Correlation rules field matching and time window support
  public/components/ContentPanel/ContentPanel.tsx
  public/components/FormFieldHeader/FormFieldHeader.tsx
  public/pages/Correlations/containers/CorrelationRuleFormModel.ts
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/store/CorrelationsStore.ts
  types/Correlations.ts
Labels: backport 2.x

#811 Ignore correlated findings whose detector is deleted
  public/store/CorrelationsStore.ts
Labels: backport 2.x, backport 2.9, backport 2.10, backport 2.11

#810 Correlation fixes
  public/pages/Correlations/containers/CorrelationRuleFormModel.ts
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
Labels: backport 2.x
