Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-02, with the labels that each got.

#404 Fixes UX issues with edit detector pages
  cypress/fixtures/sample_index_settings.json
  cypress/integration/1_detectors.spec.js
  cypress/integration/4_findings.spec.js
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateFieldMappings/UpdateFieldMappings.tsx
  public/pages/Detectors/components/UpdateRules/UpdateRules.tsx
  public/utils/constants.ts
  public/utils/helpers.tsx
Labels: backport 2.x

#372 Feature/update vertical domain
  package.json
  public/pages/Overview/utils/__snapshots__/helper.test.ts.snap
  public/pages/Overview/utils/helper.test.ts
  public/pages/Overview/utils/helpers.ts
  tsconfig.json
  yarn.lock
Labels: backport 2.x

#415 Baselined MAINTAINERS and CODEOWNERS docs.
  CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x

#405 [BUG] Wrong breadcrumbs after browser reload on edit detectors page #395
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
Labels: backport 2.x, backport 2.5

#429 [Backport 2.x] [Feature] create detector | make data source multi select field (#424)
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldMappingsTable.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.test.tsx
Labels: backport 2.6

#432 Improvements for field mappings
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldMappingsTable.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/FieldMappings/EditFieldMapping.tsx
  public/pages/Detectors/containers/FieldMappings/__snapshots__/EditFieldMappings.test.tsx.snap
Labels: backport 2.x, backport 2.6

#439 Added new log types
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/utils/constants.ts
  public/pages/Rules/utils/constants.ts
  public/utils/constants.ts
Labels: backport 2.x, backport 2.6

#438 release notes 2.6.0
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.6.0.0.md
Labels: backport 2.x, backport 2.6

#437 added create dashboard feature
  cypress/integration/1_detectors.spec.js
  cypress/integration/5_integrations.spec.js
  public/models/interfaces.ts
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/DetectorBasicDetailsView.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/__snapshots__/DetectorBasicDetailsView.test.tsx.snap
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Main/Main.tsx
  public/security_analytics_app.tsx
  public/services/IndexService.ts
  public/services/SavedObjectService.ts
  public/services/index.ts
  public/store/config/savedObjects/cloudtrail.ts
  public/store/config/savedObjects/s3.ts
  public/store/config/savedObjects/vpc-flow-logs.ts
  public/store/savedObjectsConfig.ts
  public/utils/constants.ts
  server/models/interfaces/index.ts
  server/routes/IndexRoutes.ts
  server/services/IndexService.ts
  server/utils/constants.ts
  test/mocks/Detectors/containers/DetectorDetails/DetectorDetails.mock.ts
  test/mocks/services/savedObjectService.mock.ts
  types/SavedObjectConfig.ts
  types/index.ts
  types/services/IIndexService.ts
  types/services/ISavedObjectsService.ts
  types/services/index.ts
Labels: backport 2.x, backport 2.6

#446 Fix Node.js and Yarn installation in CI
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.x, backport 2.6

#451 [Backport 2.x] Fix Node.js and Yarn installation in CI
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
Labels: backport 2.6

#453 Updated release notes for 2.6
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.6.0.0.md
Labels: backport 2.x, backport 2.6

#456 Minor UI improvements
  public/pages/Detectors/containers/Detectors/Detectors.tsx
  public/pages/Overview/models/OverviewViewModel.ts
Labels: backport 2.x

#422 Bumped version to 2.6
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  opensearch_dashboards.json
  package.json
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  test/mocks/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.mock.ts
Labels: backport 2.x, backport 2.6
