Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-10, with the labels that each got.

#732 Ux improvements for correlations page
  public/pages/Correlations/components/CorrelationGraph.tsx
  public/pages/Correlations/components/FindingCard.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
Labels: backport 2.x

#738 [Part 2] Simplify detector creation UX
  cypress/integration/1_detectors.spec.js
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/__snapshots__/AlertConditionPanel.test.tsx.snap
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/utils/helpers.ts
  public/pages/CreateDetector/components/ConfigureFieldMapping/components/RequiredFieldMapping/FieldMappingsTable.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRules.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorType/DetectorType.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/components/ReviewAndCreate/containers/ReviewAndCreate.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/CreateDetector/models/types.ts
  public/pages/CreateDetector/utils/constants.ts
  public/pages/Detectors/components/UpdateAlertConditions/UpdateAlertConditions.tsx
  public/pages/Detectors/components/UpdateAlertConditions/__snapshots__/UpdateAlertConditions.test.tsx.snap
  public/pages/Detectors/containers/Detectors/Detectors.tsx
  public/pages/Detectors/containers/FieldMappings/__snapshots__/EditFieldMappings.test.tsx.snap
  public/pages/Overview/components/GettingStarted/GettingStartedPopup.tsx
  public/pages/Overview/components/Widgets/Summary.tsx
  public/pages/Overview/containers/Overview/Overview.tsx
  types/Detector.ts
Labels: backport 2.x

#741 Added categories for log types
  cypress/integration/2_rules.spec.js
  cypress/integration/3_alerts.spec.js
  cypress/integration/4_findings.spec.js
  cypress/support/helpers.js
  public/components/Utility/LogCategoryOption.tsx
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/pages/Correlations/utils/helpers.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorType/DetectorType.tsx
  public/pages/Detectors/containers/Detectors/Detectors.tsx
  public/pages/Detectors/containers/Detectors/__snapshots__/Detectors.test.tsx.snap
  public/pages/LogTypes/components/LogTypeForm.tsx
  public/pages/LogTypes/utils/constants.ts
  public/pages/LogTypes/utils/helpers.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorForm.tsx
  public/pages/Rules/utils/constants.ts
  public/pages/Rules/utils/helpers.tsx
  public/store/LogTypeStore.ts
  public/utils/constants.tsx
  public/utils/helpers.tsx
  types/LogTypes.ts
Labels: backport 2.x

#745 Enhance log type filters correlations
  public/pages/Correlations/components/FilterGroup.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
  public/pages/Correlations/utils/constants.tsx
  public/pages/LogTypes/components/LogTypeForm.tsx
  public/pages/LogTypes/utils/helpers.tsx
  public/store/CorrelationsStore.ts
  public/store/LogTypeStore.ts
  public/utils/constants.ts
  public/utils/helpers.tsx
  server/services/RuleService.ts
Labels: backport 2.x, backport 2.11

#756 Added 2.11 release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.11.0.0.md
Labels: backport 2.x, backport 2.11

#753 Improved display of log types.
  .github/workflows/cypress-workflow.yml
  cypress/integration/1_detectors.spec.js
  cypress/integration/2_rules.spec.js
  cypress/integration/3_alerts.spec.js
  cypress/integration/4_findings.spec.js
  cypress/integration/5_integrations.spec.js
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/pages/Correlations/utils/constants.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/utils/constants.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorType/DetectorType.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/DetectorBasicDetailsView.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/__snapshots__/DetectorBasicDetailsView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/LogTypes/utils/constants.ts
  public/pages/LogTypes/utils/helpers.tsx
  public/pages/Overview/components/Widgets/Summary.tsx
  public/pages/Rules/components/RuleContentViewer/RuleContentViewer.tsx
  public/pages/Rules/components/RuleContentViewer/__snapshots__/RuleContentViewer.test.tsx.snap
  public/pages/Rules/components/RuleEditor/RuleEditorForm.tsx
  public/store/LogTypeStore.ts
  public/store/RulesStore.ts
  public/utils/helpers.tsx
Labels: backport 2.x, backport 2.10, backport 2.11

#752 Omit field from mapping payload if it matches index field; Abort detector creation when mapping has failed
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/services/FieldMappingService.ts
Labels: backport 2.x, backport 2.11

#762 Threat intel feed support for detector creation
  .github/workflows/cypress-workflow.yml
  cypress/integration/1_detectors.spec.js
  cypress/integration/3_alerts.spec.js
  models/interfaces.ts
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/Correlations/containers/CorrelationRules.tsx
  public/pages/Correlations/utils/helpers.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/__snapshots__/AlertConditionPanel.test.tsx.snap
  public/pages/CreateDetector/components/ConfigureAlerts/containers/ConfigureAlerts.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/utils/helpers.ts
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/ConfigureFieldMapping/utils/constants.ts
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRules.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDetails/DetectorBasicDetailsForm.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/DetectorSchedule.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorType/DetectorType.tsx
  public/pages/CreateDetector/components/DefineDetector/components/ThreatIntelligence/ThreatIntelligence.tsx
  public/pages/CreateDetector/components/DefineDetector/containers/DefineDetector.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/AlertTriggerView/__snapshots__/AlertTriggerView.test.tsx.snap
  public/pages/Detectors/components/DetectorBasicDetailsView/DetectorBasicDetailsView.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/__snapshots__/DetectorBasicDetailsView.test.tsx.snap
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/components/UpdateAlertConditions/__snapshots__/UpdateAlertConditions.test.tsx.snap
  public/pages/Detectors/components/UpdateBasicDetails/UpdateBasicDetails.tsx
  public/pages/Detectors/components/UpdateBasicDetails/__snapshots__/UpdateDetectorBasicDetails.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/containers/Detectors/__snapshots__/Detectors.test.tsx.snap
  public/pages/Detectors/containers/FieldMappings/__snapshots__/EditFieldMappings.test.tsx.snap
  public/pages/Findings/components/CreateAlertFlyout.tsx
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Findings/models/interfaces.ts
  public/pages/Overview/models/OverviewViewModel.ts
  public/pages/Overview/models/interfaces.ts
  public/pages/Rules/utils/constants.ts
  public/store/DetectorsStore.tsx
  public/store/LogTypeStore.ts
  public/utils/constants.ts
  public/utils/helpers.tsx
  server/models/interfaces/FieldMappings.ts
  server/services/FindingsService.ts
  test/mocks/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertCondition.mock.ts
  types/Alert.ts
  types/Correlations.ts
  types/Detector.ts
Labels: backport 2.x, backport 2.11
