Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2023-06, with the labels that each got.

#621 [Backport 2.8] Fixed missing import.
  public/pages/Rules/components/RuleEditor/components/YamlRuleEditorComponent/RuleTagsComboBox.tsx
Labels: v2.8.0

#625 Custom rules multiply on the create detector page after switching log types
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRulesTable.tsx
Labels: backport 2.x, backport 2.7, backport 2.8

#622 Change the order of the sections
  cypress/integration/1_detectors.spec.js
  cypress/integration/2_rules.spec.js
  cypress/support/helpers.js
  cypress/support/index.d.ts
  package.json
  public/app.scss
  public/pages/Rules/components/DeleteModal/DeleteRuleModal.test.tsx
  public/pages/Rules/components/DeleteModal/DeleteRuleModal.tsx
  public/pages/Rules/components/DeleteModal/__snapshots__/DeleteRuleModal.test.tsx.snap
  public/pages/Rules/components/RuleEditor/DetectionVisualEditor.test.tsx
  public/pages/Rules/components/RuleEditor/DetectionVisualEditor.tsx
  public/pages/Rules/components/RuleEditor/FieldTextArray.tsx
  public/pages/Rules/components/RuleEditor/FormSubmissionErrorToastNotification.test.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorContainer.test.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorForm.scss
  public/pages/Rules/components/RuleEditor/RuleEditorForm.test.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorForm.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorFormModel.ts
  public/pages/Rules/components/RuleEditor/__snapshots__/DetectionVisualEditor.test.tsx.snap
  public/pages/Rules/components/RuleEditor/__snapshots__/FormSubmissionErrorToastNotification.test.tsx.snap
  public/pages/Rules/components/RuleEditor/__snapshots__/RuleEditorContainer.test.tsx.snap
  public/pages/Rules/components/RuleEditor/__snapshots__/RuleEditorForm.test.tsx.snap
  public/pages/Rules/components/RuleEditor/components/FieldTextArray.test.tsx
  public/pages/Rules/components/RuleEditor/components/FieldTextArray.tsx
  public/pages/Rules/components/RuleEditor/components/SelectionExpField.scss
  public/pages/Rules/components/RuleEditor/components/SelectionExpField.test.tsx
  public/pages/Rules/components/RuleEditor/components/SelectionExpField.tsx
  public/pages/Rules/components/RuleEditor/components/YamlRuleEditorComponent/RuleTagsComboBox.tsx
  public/pages/Rules/components/RuleEditor/components/__snapshots__/FieldTextArray.test.tsx.snap
  public/pages/Rules/components/RuleEditor/components/__snapshots__/SelectionExpField.test.tsx.snap
  public/pages/Rules/components/RuleEditor/mappers.ts
  public/pages/Rules/components/RuleViewerFlyout/RuleViewerFlyout.tsx
  public/pages/Rules/components/RulesTable/RulesTable.test.tsx
  public/pages/Rules/components/RulesTable/__snapshots__/RulesTable.test.tsx.snap
  public/pages/Rules/containers/EditRule/EditRule.tsx
  public/pages/Rules/containers/Rules/Rules.tsx
  public/utils/validation.ts
  test/mocks/Rules/components/DeleteModal/DeleteRuleModal.mock.ts
  test/mocks/Rules/components/RuleEditor/DetectionVisualEditor.mock.ts
  test/mocks/Rules/components/RuleEditor/RuleEditorContainer.mock.ts
  test/mocks/Rules/components/RuleEditor/RuleEditorForm.mock.ts
  test/mocks/Rules/components/RuleEditor/components/FieldTextArray.mock.ts
  test/mocks/Rules/components/RuleEditor/components/SelectionExpField.mock.ts
  test/mocks/Rules/components/RulesTable/RulesTable.mock.ts
  test/mocks/Rules/index.ts
  test/setup.jest.ts
  yarn.lock
Labels: backport 2.x

#619 UX updates for correlations
  public/pages/Correlations/components/CorrelationGraph.tsx
  public/pages/Correlations/components/ExperimentalBanner.tsx
  public/pages/Correlations/components/FilterGroup.tsx
  public/pages/Correlations/components/FindingCard.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
  public/pages/Correlations/utils/constants.tsx
  public/pages/Correlations/utils/helpers.tsx
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Findings/components/CorrelationsTable/CorrelationsTable.tsx
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Rules/utils/constants.ts
  public/pages/Rules/utils/helpers.tsx
  public/store/CorrelationsStore.ts
  public/utils/helpers.tsx
  types/Correlations.ts
Labels: backport 2.x
