Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2024-03, with the labels that each got.

#919 Fetching channel types using API; updated type imports
  public/pages/CreateDetector/components/ConfigureAlerts/utils/constants.ts
  public/pages/CreateDetector/components/ConfigureAlerts/utils/helpers.ts
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Detectors/components/UpdateAlertConditions/__snapshots__/UpdateAlertConditions.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/AlertTriggersView.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/security_analytics_app.tsx
  public/services/NotificationsService.ts
  server/clusters/addNotificationsMethods.ts
  server/models/interfaces/Notifications.ts
  server/models/interfaces/index.ts
  server/routes/NotificationsRoutes.ts
  server/services/NotificationsService.ts
  server/utils/constants.ts
  types/Notification.ts
Labels: backport 2.x

#920 Alert severity moved out of notifications toggle
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/AlertConditionPanel.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/__snapshots__/AlertConditionPanel.test.tsx.snap
Labels: backport 2.x, backport 2.11, backport 2.12

#899 Add workflow to build and install security analytics dashboards plugin
  .github/workflows/cypress-workflow.yml
  .github/workflows/unit-tests-workflow.yml
  .github/workflows/verify-binary-installation.yml
Labels: backport 2.x

#965 Fixed logic to get all alerts for a detector
  public/store/AlertsStore.ts
Labels: backport 2.x, backport 2.13

#966 [2.x] Backport missing commits from #924, #942, #965
  common/constants.ts
  cypress/integration/1_detectors.spec.js
  cypress/integration/2_rules.spec.js
  models/interfaces.ts
  public/pages/Alerts/components/AlertFlyout/AlertFlyout.tsx
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Correlations/components/FindingCard.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
  public/pages/Correlations/utils/constants.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/utils/dummyData.ts
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Main/Main.tsx
  public/pages/Overview/models/OverviewViewModel.ts
  public/pages/Overview/models/interfaces.ts
  public/pages/Rules/components/RuleContentViewer/RuleContentYamlViewer.test.tsx
  public/pages/Rules/components/RuleContentViewer/RuleContentYamlViewer.tsx
  public/pages/Rules/components/RuleEditor/DetectionVisualEditor.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorContainer.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorForm.tsx
  public/pages/Rules/components/RuleEditor/RuleEditorFormModel.ts
  public/pages/Rules/components/RuleEditor/__snapshots__/DetectionVisualEditor.test.tsx.snap
  public/pages/Rules/components/RuleEditor/__snapshots__/RuleEditorContainer.test.tsx.snap
  public/pages/Rules/components/RuleEditor/__snapshots__/RuleEditorForm.test.tsx.snap
  public/pages/Rules/components/RuleEditor/components/YamlRuleEditorComponent/YamlRuleEditorComponent.test.tsx
  public/pages/Rules/components/RuleEditor/components/YamlRuleEditorComponent/YamlRuleEditorComponent.tsx
  public/pages/Rules/components/RuleEditor/mappers.ts
  public/pages/Rules/containers/DuplicateRule/DuplicateRule.tsx
  public/pages/Rules/containers/EditRule/EditRule.tsx
  public/pages/Rules/containers/ImportRule/ImportRule.tsx
  public/pages/Rules/utils/constants.ts
  public/pages/Rules/utils/helpers.tsx
  public/pages/Rules/utils/mappers.ts
  public/services/AlertsService.ts
  public/services/DetectorService.ts
  public/services/FindingsService.ts
  public/services/RuleService.ts
  public/store/AlertsStore.ts
  public/store/CorrelationsStore.ts
  public/store/DataStore.ts
  public/store/FindingsStore.ts
  public/store/RulesStore.ts
  public/utils/validation.ts
  server/clusters/addAlertsMethods.ts
  server/clusters/addFindingsMethods.ts
  server/models/interfaces/Alerts.ts
  server/models/interfaces/Findings.ts
  server/models/interfaces/Rules.ts
  server/routes/AlertRoutes.ts
  server/routes/FindingsRoutes.ts
  server/services/FindingsService.ts
  server/services/RuleService.ts
  test/mocks/Alerts/components/AlertFlyout/AlertFlyout.mock.ts
  test/mocks/Rules/components/RuleEditor/RuleEditorForm.mock.ts
  types/Correlations.ts
  types/Detector.ts
  types/Finding.ts
  types/Rule.ts
Labels: backport 2.13
