Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2024-09, with the labels that each got.

#1125 Update url with data source id; redirect on reload if ds id not present; minor fixes
  public/components/MDS/DataSourceMenuWrapper.tsx
  public/pages/Main/Main.tsx
  public/pages/ThreatIntel/containers/AddThreatIntelSource/AddThreatIntelSource.tsx
  public/pages/ThreatIntel/containers/Overview/ThreatIntelOverview.tsx
  public/security_analytics_app.tsx
  types/shared.ts
Labels: backport 2.x, backport 2.17

#1129 New home page related UI updates
  public/components/Charts/ChartContainer.scss
  public/components/DataSourceThreatAlertsCard/DataSourceThreatAlertsCard.tsx
  public/components/MDS/DataSourceMenuWrapper.tsx
  public/components/PageHeader/PageHeader.tsx
  public/pages/CreateDetector/components/ConfigureAlerts/components/AlertCondition/__snapshots__/AlertConditionPanel.test.tsx.snap
  public/pages/Findings/components/FindingsTable/ThreatIntelFindingsTable.tsx
  public/pages/Main/Main.tsx
  public/pages/Overview/components/GettingStarted/GettingStartedContent.tsx
  public/pages/Overview/components/GettingStarted/GettingStartedPopup.tsx
  public/pages/Overview/components/Widgets/RecentAlertsWidget.tsx
  public/pages/Overview/components/Widgets/RecentFindingsWidget.tsx
  public/pages/Overview/components/Widgets/RecentThreatIntelFindingsWidget.tsx
  public/pages/Overview/components/Widgets/Summary.tsx
  public/pages/Overview/components/Widgets/WidgetContainer.tsx
  public/pages/Overview/containers/Overview/Overview.tsx
  public/pages/Overview/models/OverviewViewModel.ts
  public/pages/Overview/utils/constants.ts
  public/pages/Rules/components/RuleEditor/RuleEditorForm.tsx
  public/pages/Rules/containers/CreateRule/CreateRule.tsx
  public/pages/ThreatIntel/containers/Overview/ThreatIntelOverview.tsx
  public/pages/ThreatIntel/utils/helpers.ts
  public/plugin.ts
  public/store/CorrelationsStore.ts
  public/utils/constants.ts
  public/utils/helpers.tsx
  types/Correlations.ts
  types/Overview.ts
Labels: backport 2.x, backport 2.17

#1133 Fixed CVEs.
  package.json
  yarn.lock
Labels: backport 2.x, v2.17.0, backport 2.17

#1136 Made import more specific to avoid importing incorrect modules
  public/utils/helpers.tsx
Labels: backport 2.x, backport 2.17

#1141 Added release notes for 2.17
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.17.0.0.md
Labels: backport 2.x, v2.17.0, backport 2.17

#1149 Pass through remaining location arguments when updating the url query params
  public/pages/Main/Main.tsx
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#1160 Fix findings page crash and rule severity correctness
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/Rules/utils/constants.ts
  public/store/CorrelationsStore.ts
Labels: backport 2.x, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17
