Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2024-10, with the labels that each got.

#1176 Bug fixes for threat intel, duplicate findings, and breadcrumbs path
  public/pages/Overview/components/Widgets/RecentThreatIntelFindingsWidget.tsx
  public/pages/ThreatIntel/components/ThreatIntelSourceDetails/ThreatIntelSourceDetails.tsx
  public/pages/ThreatIntel/components/ThreatIntelSourcesList/ThreatIntelSourcesList.tsx
  public/store/FindingsStore.ts
  public/utils/constants.ts
Labels: backport 2.x

#1174 Fit and Finish UX Fixes
  public/components/ContentPanel/ContentPanel.tsx
  public/components/ContentPanel/__snapshots__/ContentPanel.test.tsx.snap
  public/pages/Alerts/components/ThreatIntelAlertsTable/ThreatIntelAlertsTable.tsx
  public/pages/Alerts/containers/Alerts/Alerts.tsx
  public/pages/Alerts/containers/Alerts/__snapshots__/Alerts.test.tsx.snap
  public/pages/Correlations/containers/CorrelationRules.tsx
  public/pages/Correlations/containers/CorrelationsContainer.tsx
  public/pages/CreateDetector/containers/CreateDetector.tsx
  public/pages/Detectors/components/DetectorBasicDetailsView/__snapshots__/DetectorBasicDetailsView.test.tsx.snap
  public/pages/Detectors/components/DetectorRulesView/__snapshots__/DetectorRulesView.test.tsx.snap
  public/pages/Detectors/components/FieldMappingsView/__snapshots__/FieldMappingsView.test.tsx.snap
  public/pages/Detectors/components/UpdateRules/__snapshots__/UpdateDetectorRules.test.tsx.snap
  public/pages/Detectors/containers/AlertTriggersView/__snapshots__/AlertTriggersView.test.tsx.snap
  public/pages/Detectors/containers/Detector/DetectorDetails.tsx
  public/pages/Detectors/containers/Detector/__snapshots__/DetectorDetails.test.tsx.snap
  public/pages/Detectors/containers/DetectorDetailsView/DetectorDetailsView.tsx
  public/pages/Detectors/containers/DetectorDetailsView/__snapshots__/DetectorDetailsView.test.tsx.snap
  public/pages/Detectors/containers/Detectors/Detectors.tsx
  public/pages/Detectors/containers/Detectors/__snapshots__/Detectors.test.tsx.snap
  public/pages/Findings/components/FindingsTable/FindingsTable.tsx
  public/pages/Findings/components/FindingsTable/ThreatIntelFindingsTable.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/LogTypes/utils/helpers.tsx
  public/pages/Overview/components/Widgets/RecentAlertsWidget.tsx
  public/pages/Overview/components/Widgets/RecentFindingsWidget.tsx
  public/pages/Overview/components/Widgets/RecentThreatIntelFindingsWidget.tsx
  public/pages/Overview/components/Widgets/Summary.tsx
  public/pages/Overview/components/Widgets/TopRulesWidget.tsx
  public/pages/Overview/containers/Overview/Overview.tsx
  public/pages/Overview/utils/constants.ts
  public/pages/Rules/components/RulesTable/__snapshots__/RulesTable.test.tsx.snap
  public/pages/Rules/containers/Rules/Rules.tsx
  public/pages/Rules/utils/helpers.tsx
  public/plugin.ts
  public/utils/constants.ts
  public/utils/helpers.tsx
Labels: backport 2.x

#1175 [Fit&Finish] Security analytics overview page
  public/pages/Overview/containers/Overview/Overview.tsx
  public/plugin.ts
  public/services/utils/constants.ts
  public/utils/helpers.tsx
Labels: backport 2.x

#1180 edit correlation Alert Trigger fix
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/store/CorrelationsStore.ts
  types/Correlations.ts
Labels: backport 2.x

#1188 fix: Update getting started cards content and visual design
  public/pages/Overview/utils/constants.ts
Labels: backport 2.x

#1190 Added HOURS option for source refresh interval.
  public/pages/ThreatIntel/components/ThreatIntelSourceDetails/ThreatIntelSourceDetails.tsx
  public/pages/ThreatIntel/containers/AddThreatIntelSource/AddThreatIntelSource.tsx
Labels: backport 2.x

#1192 fix: data source picker remount multiple times
  public/components/DataSourceThreatAlertsCard/DataSourceThreatAlertsCard.tsx
Labels: backport 2.x, backport 2.17, backport 2.18

#1200 Make data source default cluster for threat alerts card
  public/components/DataSourceThreatAlertsCard/DataSourceThreatAlertsCard.tsx
Labels: backport 2.x, backport 2.18

#1206 Fix data source picker for threat alerts card
  public/components/DataSourceThreatAlertsCard/DataSourceThreatAlertsCard.tsx
  public/services/AlertsService.ts
  public/services/DetectorService.ts
  public/store/AlertsStore.ts
  types/Alert.ts
Labels: backport 2.x, backport 2.18

#1205 Added 2.18.0 release notes.
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.18.0.0.md
Labels: backport 2.x, v2.18.0, backport 2.18

#1216 [MDS] Do not decode datasource id from url; update global state on datasource change
  public/pages/Main/Main.tsx
  public/security_analytics_app.tsx
Labels: backport 2.x, backport 2.17, backport 2.18
