Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2024-02, with the labels that each got.

#862 Add check for mappings view API call during create detector
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
Labels: backport 2.x

#849 Ask for mapping of threat intel feeds related fields only when threat intel is enabled
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
Labels: backport 2.x

#864 Show aliases in data source options for detector and correlation rule creation
  cypress/integration/1_detectors.spec.js
  public/pages/Correlations/containers/CreateCorrelationRule.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectionRules/DetectionRules.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorDataSource/DetectorDataSource.tsx
  public/pages/Detectors/models/interfaces.ts
  public/services/IndexService.ts
  public/utils/helpers.tsx
  server/models/interfaces/index.ts
  server/routes/IndexRoutes.ts
  server/services/IndexService.ts
  server/utils/constants.ts
Labels: backport 2.x

#845 [Bugfix] Add already mapped log index fields to list of mapping options
  public/pages/CreateDetector/components/ConfigureFieldMapping/containers/ConfigureFieldMapping.tsx
Labels: backport 2.x, backport 2.9, backport 2.10, backport 2.11, backport 2.12

#875 Add missing modules common and types
  .opensearch_dashboards-plugin-helpers.json
  tsconfig.json
Labels: backport 2.x, v2.12.0, backport 2.12

#879 Release notes for 2.12.0
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.12.0.0.md
Labels: backport 2.x, backport 2.12

#882 Update tsconfig and helper config
  .opensearch_dashboards-plugin-helpers.json
  tsconfig.json
Labels: backport 2.x, backport 2.12

#874 [CVE-2023-46234 fix] Updated yarn.lock to use latest dependencies
  yarn.lock
Labels: backport 2.x, backport 2.12

#891 Pinned vis-data to 7.1.6 to mitigate build failure
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.12
