Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2024-05, with the labels that each got.

#997 Added release notes for 2.14.0
  release-notes/opensearch-security-analytics-dashboards.release-notes-2.14.0.0.md
Labels: backport 2.x, backport 2.14

#1000 Added check before running husky install during post install
  package.json
Labels: backport 2.x, backport 2.14

#1014 Enhanced UI for rendering multiple documents in finding details flyout
  cypress/integration/3_alerts.spec.js
  public/pages/Findings/components/FindingDetailsFlyout.tsx
Labels: backport 2.x, backport 2.11, backport 2.12, backport 2.13, backport 2.14

#1008 [MDS][Part 2] Added server-side glue code to use data source id when getting opensearch client for making API calls to cluster
  public/pages/Alerts/containers/Alerts/__snapshots__/Alerts.test.tsx.snap
  public/pages/Detectors/components/UpdateAlertConditions/__snapshots__/UpdateAlertConditions.test.tsx.snap
  public/pages/Detectors/containers/Detectors/__snapshots__/Detectors.test.tsx.snap
  server/models/interfaces/Alerts.ts
  server/plugin.ts
  server/routes/AlertRoutes.ts
  server/routes/CorrelationRoutes.ts
  server/routes/DetectorRoutes.ts
  server/routes/FieldMappingRoutes.ts
  server/routes/FindingsRoutes.ts
  server/routes/IndexRoutes.ts
  server/routes/LogTypeRoutes.ts
  server/routes/MetricsRoutes.ts
  server/routes/NotificationsRoutes.ts
  server/routes/OpenSearchRoutes.ts
  server/routes/RuleRoutes.ts
  server/services/AlertService.ts
  server/services/CorrelationService.ts
  server/services/DetectorService.ts
  server/services/FieldMappingService.ts
  server/services/FindingsService.ts
  server/services/IndexService.ts
  server/services/LogTypeService.ts
  server/services/MDSEnabledClientService.ts
  server/services/NotificationsService.ts
  server/services/OpenSearchService.ts
  server/services/RuleService.ts
  server/utils/helpers.ts
  test/mocks/useContext.mock.ts
  test/setup.jest.ts
  types/Alert.ts
  types/DataSource.ts
  types/DataSourceContext.ts
  types/Overview.ts
  types/index.ts
Labels: backport 2.x
