Repository opensearch-project/security-analytics-dashboards-plugin, pull requests merged in 2024-07, with the labels that each got.

#1071 [Threat intel] Fetch up to 10k source configs and iocs under source details
  public/pages/ThreatIntel/containers/ThreatIntelSource/ThreatIntelSource.tsx
  server/services/ThreatIntelService.ts
Labels: backport 2.x, backport 2.15

#1068 [Threat intel][part 3] Support for source type URL_Download and logic to activate/deactivate source
  public/pages/ThreatIntel/components/ThreatIntelSourceDetails/ThreatIntelSourceDetails.tsx
  public/pages/ThreatIntel/containers/Overview/ThreatIntelOverview.tsx
  public/pages/ThreatIntel/containers/ThreatIntelSource/ThreatIntelSource.tsx
  types/ThreatIntel.ts
Labels: backport 2.x, backport 2.15

#1076 Updated IOCTypes.
  common/constants.ts
Labels: backport 2.x, backport 2.15

#1080 [Threat intel] Fixed ui issues
  common/helpers.ts
  public/app.scss
  public/components/DeleteModal/DeleteModal.tsx
  public/components/Notifications/NotificationForm.tsx
  public/pages/CreateDetector/components/DefineDetector/components/DetectorSchedule/Interval.tsx
  public/pages/Detectors/components/AlertTriggerView/AlertTriggerView.tsx
  public/pages/Findings/components/FindingDetailsFlyout.tsx
  public/pages/Findings/components/FindingsTable/ThreatIntelFindingsTable.tsx
  public/pages/Findings/containers/Findings/Findings.tsx
  public/pages/ThreatIntel/components/ConfigureThreatIntelAlertTriggers/ConfigureThreatIntelAlertTriggers.tsx
  public/pages/ThreatIntel/components/SelectLogSourcesForm/SelectThreatIntelLogSourcesForm.tsx
  public/pages/ThreatIntel/components/ThreatIntelAlertTriggerForm/ThreatIntelAlertTriggerForm.tsx
  public/pages/ThreatIntel/components/ThreatIntelLogSourcesFlyout/ThreatIntelLogSourcesFlyout.tsx
  public/pages/ThreatIntel/components/ThreatIntelSourceDetails/ThreatIntelSourceDetails.tsx
  public/pages/ThreatIntel/containers/AddThreatIntelSource/AddThreatIntelSource.scss
  public/pages/ThreatIntel/containers/AddThreatIntelSource/AddThreatIntelSource.tsx
  public/pages/ThreatIntel/containers/ScanConfiguration/ThreatIntelScanConfigForm.tsx
  public/pages/ThreatIntel/containers/ThreatIntelSource/ThreatIntelSource.tsx
  public/pages/ThreatIntel/utils/constants.ts
  public/pages/ThreatIntel/utils/helpers.ts
  public/utils/helpers.tsx
  public/utils/validation.ts
  server/clusters/addFieldMappingMethods.ts
  server/services/FieldMappingService.ts
Labels: backport 2.x, backport 2.15

#1084 side nav changes for SA
  public/pages/Main/Main.tsx
  public/plugin.ts
  public/utils/constants.ts
Labels: backport 2.x

#1090 [CVE-2024-4068] Pinned package version for braces
  package.json
  yarn.lock
Labels: backport 2.x, backport 2.16

#1093 [navigation]feat: update nav category and workspaceAvailability
  public/plugin.ts
Labels: backport 2.x, backport 2.16

#1095 Updated snapshots to fix unit test CI
  public/pages/Alerts/containers/Alerts/__snapshots__/Alerts.test.tsx.snap
Labels: backport 2.x, backport 2.16
